[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_mysql", "php83Extensions.bcmath", "php83Extensions.gd", "php83Extensions.zip", "php83Extensions.intl", "nodejs_20", "git", "unzip", "curl"]

[phases.build]
cmds = [
    "npm install", 
    "npm run build", 
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs --no-scripts"
]

[start]
cmd = "php artisan package:discover --ansi && php artisan storage:link && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
