[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_mysql", "php83Extensions.bcmath", "php83Extensions.gd", "php83Extensions.zip", "php83Extensions.intl", "php83Extensions.opcache", "nodejs_20", "git", "unzip", "curl", "php83Packages.composer", "nginx"]

[phases.build]
cmds = [
    "npm install", 
    "npm run build", 
    "mkdir -p bootstrap/cache storage/framework/views storage/framework/sessions storage/framework/testing storage/framework/cache storage/logs",
    "composer install --optimize-autoloader --ignore-platform-reqs --no-scripts",
    "chmod +x start.sh"
]

[start]
cmd = "bash start.sh"
