[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_mysql", "php83Extensions.bcmath", "php83Extensions.gd", "php83Extensions.zip", "php83Extensions.intl", "nodejs_20"]

[phases.build]
cmds = [
    "npm install", 
    "npm run build", 
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
