[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_mysql", "php83Extensions.bcmath", "php83Extensions.gd", "php83Extensions.zip", "php83Extensions.intl", "php83Extensions.opcache", "nodejs_20", "git", "unzip", "curl", "php83Packages.composer"]

[phases.build]
cmds = [
    "npm install", 
    "npm run build", 
    "mkdir -p bootstrap/cache storage/framework/views storage/framework/sessions storage/framework/testing storage/framework/cache storage/logs",
    "composer install --optimize-autoloader --ignore-platform-reqs --no-scripts"
]

[start]
cmd = "chmod -R 777 storage bootstrap/cache && php artisan package:discover --ansi && php artisan storage:link && php artisan ns:translate --symlink --force && php artisan modules:symlink && php artisan migrate --force && php artisan optimize && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
